// Typed wrappers over the Tauri commands, generated by Tauri Specta.
//
// The command signatures and payload types live in bindings.ts, which the
// Rust build regenerates from the `#[specta::specta]` command definitions —
// this file only unwraps the generated `{ status: "ok" | "error" }` envelope
// back into plain promises so the stores can keep their error handling.
// Errors surface as thrown strings.

import { commands } from "./bindings";
import { Channel } from "@tauri-apps/api/core";
import type { Model, PluginOpEvent, PluginOpKind, Provider, Surface } from "./bindings";

// Unwrap the generated result envelope; a rejected command surfaces as a
// thrown string, matching the previous hand-written invoke wrappers.
async function unwrap<T>(
  result: Promise<{ status: "ok"; data: T } | { status: "error"; error: string }>,
): Promise<T> {
  const outcome = await result;
  if (outcome.status === "error") {
    throw outcome.error;
  }
  return outcome.data;
}

export const api = {
  // Engine overview: detection + inventory counts.
  refreshOverview: () => unwrap(commands.refreshAll()),
  // Runtime.
  runtimeStart: (profile: string) => unwrap(commands.runtimeStart(profile)),
  runtimeStop: (profile: string) => unwrap(commands.runtimeStop(profile)),
  runtimeRestart: (profile: string) => unwrap(commands.runtimeRestart(profile)),
  runtimeList: () => unwrap(commands.runtimeList()),
  openHarness: (profile: string) => unwrap(commands.openHarness(profile)),
  // Stream one task run: `onEvent` receives the task's Started / Line /
  // Finished events; the promise resolves when the run ends.
  taskRun: (profile: string, prompt: string, onEvent: (event: PluginOpEvent) => void) => {
    const channel = new Channel<PluginOpEvent>();
    channel.onmessage = onEvent;
    return unwrap(commands.taskRun(channel, profile, prompt));
  },
  // Diagnostics.
  runDoctor: () => unwrap(commands.runDoctor()),
  doctorFix: (checkId: string, mode: string) => unwrap(commands.doctorFix(checkId, mode)),
  // Scenarios (the harness calls them profiles).
  listScenarios: () => unwrap(commands.listProfiles()),
  createScenario: (name: string, surface: Surface) =>
    unwrap(commands.createScenario(name, surface)),
  renameScenario: (oldName: string, newName: string) =>
    unwrap(commands.renameProfile(oldName, newName)),
  removeScenario: (name: string) => unwrap(commands.removeProfile(name)),
  setScenarioDescription: (name: string, description: string | null) =>
    unwrap(commands.setScenarioDescription(name, description)),
  // Providers & models (per scenario).
  listProviders: (profile: string) => unwrap(commands.listProviders(profile)),
  listModels: (profile: string) => unwrap(commands.listModels(profile)),
  upsertProvider: (profile: string, provider: Provider) =>
    unwrap(commands.upsertProvider(profile, provider)),
  removeProvider: (profile: string, id: string) => unwrap(commands.removeProvider(profile, id)),
  upsertModel: (profile: string, provider: string, model: Model) =>
    unwrap(commands.upsertModel(profile, provider, model)),
  removeModel: (profile: string, provider: string, id: string) =>
    unwrap(commands.removeModel(profile, provider, id)),
  // Plugins.
  listPlugins: () => unwrap(commands.listPlugins()),
  pluginInstall: (profile: string, spec: string) => unwrap(commands.pluginInstall(profile, spec)),
  pluginCheck: (spec: string) => unwrap(commands.pluginCheck(spec)),
  pluginDisable: (profile: string, id: string) => unwrap(commands.pluginDisable(profile, id)),
  pluginEnable: (profile: string, id: string) => unwrap(commands.pluginEnable(profile, id)),
  listDisabledPlugins: () => unwrap(commands.listDisabledPlugins()),
  // Stream a plugin operation: `onEvent` receives Started / Line / Finished
  // events as they happen; the promise resolves when the operation ends.
  pluginOpStream: (
    profile: string,
    kind: PluginOpKind,
    target: string,
    onEvent: (event: PluginOpEvent) => void,
  ) => {
    const channel = new Channel<PluginOpEvent>();
    channel.onmessage = onEvent;
    return unwrap(commands.pluginOpStream(channel, profile, kind, target));
  },
  // Market.
  marketSearch: (query: string) => unwrap(commands.marketSearch(query)),
  // Snapshots.
  snapshotExport: (name: string) => unwrap(commands.snapshotExport(name)),
  snapshotImport: (name: string) => unwrap(commands.snapshotImport(name)),
  snapshotDelete: (name: string) => unwrap(commands.snapshotDelete(name)),
  snapshotList: () => unwrap(commands.snapshotList()),
  // Preferences & config.
  configExport: () => unwrap(commands.configExport()),
  configImport: () => unwrap(commands.configImport()),
  setLanguage: (language: string) => unwrap(commands.setLanguage(language)),
  setTheme: (theme: string) => unwrap(commands.setTheme(theme)),
  setCloseToTray: (enabled: boolean) => unwrap(commands.setCloseToTray(enabled)),
  setCheckUpdates: (enabled: boolean) => unwrap(commands.setCheckUpdates(enabled)),
  setNotifyUpdates: (enabled: boolean) => unwrap(commands.setNotifyUpdates(enabled)),
  autostartGet: () => unwrap(commands.autostartGet()),
  autostartSet: (enabled: boolean) => unwrap(commands.autostartSet(enabled)),
  // Market settings.
  setMarketDefaultSource: (source: string) => unwrap(commands.setMarketDefaultSource(source)),
  setMarketRefreshInterval: (seconds: number) => unwrap(commands.setMarketRefreshInterval(seconds)),
  // Advanced raw configuration files.
  advancedFileRead: (scope: string, name: string | null) =>
    unwrap(commands.advancedFileRead(scope, name)),
  advancedFileSave: (scope: string, name: string | null, content: string) =>
    unwrap(commands.advancedFileSave(scope, name, content)),
  // Updates.
  checkUpdate: () => unwrap(commands.checkUpdate()),
  updateInstall: () => unwrap(commands.updateInstall()),
  openUrl: (url: string) => unwrap(commands.openUrl(url)),
  getConfig: () => unwrap(commands.getConfig()),
};

export type {
  CheckStatus,
  CompatReport,
  DoctorCheck,
  DoctorReport,
  DisabledPlugin,
  MarketEntry,
  MarketTrust,
  Model,
  Overview,
  Plugin,
  PluginOpEvent,
  PluginOpKind,
  Profile,
  Provider,
  RuntimeInstance,
  RuntimeStatusKind,
  Surface,
  UiPrefs,
  UpdateInfo,
} from "./bindings";
