// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	refreshAll: () => typedError<Overview, string>(__TAURI_INVOKE("refresh_all")),
	runtimeStart: (profile: string) => typedError<null, string>(__TAURI_INVOKE("runtime_start", { profile })),
	runtimeStop: (profile: string) => typedError<null, string>(__TAURI_INVOKE("runtime_stop", { profile })),
	runtimeRestart: (profile: string) => typedError<null, string>(__TAURI_INVOKE("runtime_restart", { profile })),
	runtimeList: () => typedError<RuntimeInstance[], string>(__TAURI_INVOKE("runtime_list")),
	taskRun: (channel: Channel<PluginOpEvent>, profile: string, prompt: string) => typedError<null, string>(__TAURI_INVOKE("task_run", { channel, profile, prompt })),
	openHarness: (profile: string) => typedError<null, string>(__TAURI_INVOKE("open_harness", { profile })),
	runDoctor: () => typedError<DoctorReport_Serialize, string>(__TAURI_INVOKE("run_doctor")),
	doctorFix: (checkId: string, mode: string) => typedError<DoctorFixReport, string>(__TAURI_INVOKE("doctor_fix", { checkId, mode })),
	listProfiles: () => typedError<Profile[], string>(__TAURI_INVOKE("list_profiles")),
	listProviders: (profile: string) => typedError<Provider[], string>(__TAURI_INVOKE("list_providers", { profile })),
	listModels: (profile: string) => typedError<Model[], string>(__TAURI_INVOKE("list_models", { profile })),
	upsertProvider: (profile: string, provider: Provider) => typedError<null, string>(__TAURI_INVOKE("upsert_provider", { profile, provider })),
	removeProvider: (profile: string, id: string) => typedError<null, string>(__TAURI_INVOKE("remove_provider", { profile, id })),
	upsertModel: (profile: string, provider: string, model: Model) => typedError<null, string>(__TAURI_INVOKE("upsert_model", { profile, provider, model })),
	removeModel: (profile: string, provider: string, id: string) => typedError<null, string>(__TAURI_INVOKE("remove_model", { profile, provider, id })),
	createProfile: (name: string) => typedError<null, string>(__TAURI_INVOKE("create_profile", { name })),
	createScenario: (name: string, surface: Surface) => typedError<null, string>(__TAURI_INVOKE("create_scenario", { name, surface })),
	removeProfile: (name: string) => typedError<null, string>(__TAURI_INVOKE("remove_profile", { name })),
	renameProfile: (old: string, newName: string) => typedError<null, string>(__TAURI_INVOKE("rename_profile", { old, newName })),
	setScenarioDescription: (name: string, description: string | null) => typedError<null, string>(__TAURI_INVOKE("set_scenario_description", { name, description })),
	listPlugins: () => typedError<Plugin[], string>(__TAURI_INVOKE("list_plugins")),
	pluginInstall: (profile: string, spec: string) => typedError<null, string>(__TAURI_INVOKE("plugin_install", { profile, spec })),
	pluginDisable: (profile: string, id: string) => typedError<null, string>(__TAURI_INVOKE("plugin_disable", { profile, id })),
	pluginEnable: (profile: string, id: string) => typedError<null, string>(__TAURI_INVOKE("plugin_enable", { profile, id })),
	listDisabledPlugins: () => typedError<DisabledPlugin[], string>(__TAURI_INVOKE("list_disabled_plugins")),
	pluginOpStream: (channel: Channel<PluginOpEvent>, profile: string, kind: PluginOpKind, target: string) => typedError<null, string>(__TAURI_INVOKE("plugin_op_stream", { channel, profile, kind, target })),
	marketSearch: (query: string) => typedError<MarketEntry[], string>(__TAURI_INVOKE("market_search", { query })).then((v) => ((v.status === "ok" ? { ...v, data: v.data.map(i=>({...i,updated:i.updated==null?i.updated:new Date(i.updated)})) } : v) as typeof v)),
	pluginCheck: (spec: string) => typedError<CompatReport, string>(__TAURI_INVOKE("plugin_check", { spec })),
	snapshotExport: (name: string) => typedError<null, string>(__TAURI_INVOKE("snapshot_export", { name })),
	snapshotImport: (name: string) => typedError<null, string>(__TAURI_INVOKE("snapshot_import", { name })),
	snapshotList: () => typedError<string[], string>(__TAURI_INVOKE("snapshot_list")),
	snapshotDelete: (name: string) => typedError<null, string>(__TAURI_INVOKE("snapshot_delete", { name })),
	configExport: () => typedError<string | null, string>(__TAURI_INVOKE("config_export")),
	configImport: () => typedError<string | null, string>(__TAURI_INVOKE("config_import")),
	setLanguage: (language: string) => typedError<null, string>(__TAURI_INVOKE("set_language", { language })),
	setTheme: (theme: string) => typedError<null, string>(__TAURI_INVOKE("set_theme", { theme })),
	setCloseToTray: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_close_to_tray", { enabled })),
	setCheckUpdates: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_check_updates", { enabled })),
	setNotifyUpdates: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_notify_updates", { enabled })),
	autostartGet: () => typedError<boolean, string>(__TAURI_INVOKE("autostart_get")),
	autostartSet: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("autostart_set", { enabled })),
	setMarketDefaultSource: (source: string) => typedError<null, string>(__TAURI_INVOKE("set_market_default_source", { source })),
	setMarketRefreshInterval: (seconds: number) => typedError<null, string>(__TAURI_INVOKE("set_market_refresh_interval", { seconds })),
	advancedFileRead: (scope: string, name: string | null) => typedError<string | null, string>(__TAURI_INVOKE("advanced_file_read", { scope, name })),
	advancedFileSave: (scope: string, name: string | null, content: string) => typedError<null, string>(__TAURI_INVOKE("advanced_file_save", { scope, name, content })),
	checkUpdate: () => typedError<{
	current_version: string,
	latest_version: string,
	url: string,
	published_at: string,
} | null, string>(__TAURI_INVOKE("check_update")),
	updateInstall: () => typedError<UpdateInstallOutcome, string>(__TAURI_INVOKE("update_install")),
	openUrl: (url: string) => typedError<null, string>(__TAURI_INVOKE("open_url", { url })),
	getConfig: () => typedError<UiPrefs, string>(__TAURI_INVOKE("get_config")),
};

/* Constants */
export const appVersion = "0.8.1" as const;

/* Types */
export type CheckStatus = "pass" | "warn" | "fail" | "skip";

export type CompatReport = {
	status: CompatStatus,
	harness_version: string | null,
	required_range: string | null,
	message: string,
};

export type CompatStatus = "compatible" | "incompatible" | "unknown";

export type Detection = {
	found: boolean,
	harness: HarnessInfo | null,
	detail: string | null,
};

export type DisabledPlugin = {
	profile: string,
	id: string,
	spec: string,
};

export type DoctorCheck = DoctorCheck_Serialize | DoctorCheck_Deserialize;

export type DoctorCheck_Deserialize = {
	id: string,
	status: CheckStatus,
	summary: string,
	details: string | null,
	suggested_action: string | null,
	cli?: string | null,
	url?: string | null,
};

export type DoctorCheck_Serialize = {
	id: string,
	status: CheckStatus,
	summary: string,
	details: string | null,
	suggested_action: string | null,
	cli?: string | null,
	url?: string | null,
};

export type DoctorFixReport = {
	fixed: number,
};

export type DoctorReport = DoctorReport_Serialize | DoctorReport_Deserialize;

export type DoctorReport_Deserialize = {
	checks: DoctorCheck_Deserialize[],
};

export type DoctorReport_Serialize = {
	checks: DoctorCheck_Serialize[],
};

export type HarnessInfo = {
	id: string,
	name: string,
	version: string | null,
};

export type InventoryCounts = {
	profiles: number,
	providers: number,
	models: number,
	plugins: number,
};

export type MarketEntry = {
	id: string,
	name: string,
	description: string | null,
	version: string | null,
	source: MarketSource,
	trust?: MarketTrust,
	repository: string | null,
	publisher: string | null,
	updated: Date | null,
	category?: string | null,
	popularity?: number | null,
	quality?: number | null,
};

export type MarketSource = "curated" | "community";

export type MarketTrust = "official" | "vetted" | "community";

export type Model = {
	id: string,
	name: string,
	provider: string | null,
	context_window: number | null,
	max_tokens: number | null,
	input: string[] | null,
	reasoning_efforts: string | null,
	compat: string | null,
};

export type Overview = {
	detection: Detection,
	status: RuntimeStatus,
	counts: InventoryCounts,
};

export type Plugin = {
	id: string,
	name: string,
	version: string | null,
	enabled: boolean,
	profile: string,
	latest: string | null,
	outdated: boolean,
	trust?: MarketTrust | null,
};

export type PluginOpEvent = { phase: "started"; op: PluginOpKind; target: string } | { phase: "line"; text: string } | { phase: "finished"; ok: boolean; detail: string | null };

export type PluginOpKind = "install" | "remove" | "update" | "task";

export type Profile = {
	id: string,
	name: string,
	description: string | null,
};

export type Provider = {
	id: string,
	name: string,
	kind: string,
	api: string | null,
	base_url: string | null,
	api_key_env: string | null,
	compat: string | null,
};

export type RuntimeInstance = {
	profile: string,
	surface: Surface,
	status: RuntimeStatusKind,
	pid: number | null,
	port: number | null,
	url: string | null,
	message: string | null,
};

export type RuntimeStatus = {
	kind: RuntimeStatusKind,
	pid: number | null,
	message: string | null,
};

export type RuntimeStatusKind = "unknown" | "installed" | "running" | "stopped" | "error";

export type Surface = "web" | "task" | "undetermined";

export type UiPrefs = {
	language: string,
	theme: string,
	check_updates: boolean,
	notify_updates: boolean,
	close_to_tray: boolean,
	market_default_source: string,
	market_refresh_interval_seconds: number,
};

export type UpdateInfo = {
	current_version: string,
	latest_version: string,
	url: string,
	published_at: string,
};

export type UpdateInstallOutcome = {
	status: string,
	path: string | null,
	version: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

