// Typed wrappers over the Tauri commands, generated by Tauri Specta.
//
// The command signatures and payload types live in bindings.ts, which the
// Rust build regenerates from the `#[specta::specta]` command definitions —
// this file only unwraps the generated `{ status: "ok" | "error" }` envelope
// back into plain promises so the store can keep its current error handling.
// Errors surface as thrown strings.

import { commands } from "./bindings";
import type { Model, Provider } from "./bindings";

// Unwrap the generated result envelope; a rejected command surfaces as a
// thrown string, matching the previous hand-written invoke wrappers.
async function unwrap<T>(
  result: Promise<{ status: "ok"; data: T } | { status: "error"; error: string }>,
): Promise<T> {
  const outcome = await result;
  if (outcome.status === "error") {
    throw outcome.error;
  }
  return outcome.data;
}

export const api = {
  refreshAll: () => unwrap(commands.refreshAll()),
  runtimeStart: () => unwrap(commands.runtimeStart()),
  runtimeStop: () => unwrap(commands.runtimeStop()),
  runtimeRestart: () => unwrap(commands.runtimeRestart()),
  openHarness: () => unwrap(commands.openHarness()),
  runDoctor: () => unwrap(commands.runDoctor()),
  listProfiles: () => unwrap(commands.listProfiles()),
  listProviders: () => unwrap(commands.listProviders()),
  listModels: () => unwrap(commands.listModels()),
  upsertProvider: (provider: Provider) => unwrap(commands.upsertProvider(provider)),
  removeProvider: (id: string) => unwrap(commands.removeProvider(id)),
  upsertModel: (provider: string, model: Model) => unwrap(commands.upsertModel(provider, model)),
  removeModel: (provider: string, id: string) => unwrap(commands.removeModel(provider, id)),
  createProfile: (name: string) => unwrap(commands.createProfile(name)),
  removeProfile: (name: string) => unwrap(commands.removeProfile(name)),
  listPlugins: () => unwrap(commands.listPlugins()),
  listMarketSources: () => unwrap(commands.listMarketSources()),
  marketSearch: (query: string) => unwrap(commands.marketSearch(query)),
  pluginInstall: (profile: string, spec: string) => unwrap(commands.pluginInstall(profile, spec)),
  pluginCheck: (spec: string) => unwrap(commands.pluginCheck(spec)),
  pluginRemove: (profile: string, id: string) => unwrap(commands.pluginRemove(profile, id)),
  pluginUpdate: (profile: string, id: string) => unwrap(commands.pluginUpdate(profile, id)),
  snapshotExport: (name: string) => unwrap(commands.snapshotExport(name)),
  snapshotImport: (name: string) => unwrap(commands.snapshotImport(name)),
  snapshotDelete: (name: string) => unwrap(commands.snapshotDelete(name)),
  snapshotList: () => unwrap(commands.snapshotList()),
  configExport: () => unwrap(commands.configExport()),
  configImport: () => unwrap(commands.configImport()),
  setLanguage: (language: string) => unwrap(commands.setLanguage(language)),
  setTheme: (theme: string) => unwrap(commands.setTheme(theme)),
  setCloseToTray: (enabled: boolean) => unwrap(commands.setCloseToTray(enabled)),
  setCheckUpdates: (enabled: boolean) => unwrap(commands.setCheckUpdates(enabled)),
  setNotifyUpdates: (enabled: boolean) => unwrap(commands.setNotifyUpdates(enabled)),
  autostartGet: () => unwrap(commands.autostartGet()),
  autostartSet: (enabled: boolean) => unwrap(commands.autostartSet(enabled)),
  checkUpdate: () => unwrap(commands.checkUpdate()),
  updateInstall: () => unwrap(commands.updateInstall()),
  openUrl: (url: string) => unwrap(commands.openUrl(url)),
  getConfig: () => unwrap(commands.getConfig()),
};

export type {
  CheckStatus,
  CompatReport,
  DoctorReport,
  MarketEntry,
  MarketSourceInfo,
  Model,
  Overview,
  Plugin,
  Profile,
  Provider,
  UiPrefs,
  UpdateInfo,
} from "./bindings";
